name: Approve and Push to Prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy to production'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEV_IMAGE_NAME: stellarhub/dev-target
      PROD_IMAGE_NAME: stellarhub/prod-target

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Tag
      id: vars
      run: |
        if [ -z "${{ github.event.inputs.tag }}" ]; then
          TAG=latest
        else
          TAG=${{ github.event.inputs.tag }}
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Display Tag for Confirmation
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "Using tag: ${{ env.TAG }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Pull dev image
      run: docker pull ${{ env.DEV_IMAGE_NAME }}:${{ env.TAG }}

    - name: Get image digest
      id: get_digest
      run: |
        DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.DEV_IMAGE_NAME }}:${{ env.TAG }} | cut -d'@' -f2)
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV

    - name: Tag image for prod
      run: docker tag ${{ env.DEV_IMAGE_NAME }}:${{ env.TAG }} ${{ env.PROD_IMAGE_NAME }}:${{ env.TAG }}

    - name: Push prod image with provided or default tag
      run: docker push ${{ env.PROD_IMAGE_NAME }}:${{ env.TAG }}

    - name: Push prod image with latest tag
      run: |
        docker tag ${{ env.PROD_IMAGE_NAME }}:${{ env.TAG }} ${{ env.PROD_IMAGE_NAME }}:latest
        docker push ${{ env.PROD_IMAGE_NAME }}:latest

    - name: Save tag information to JSON
      run: |
        echo "{\"image_name\": \"${{ env.PROD_IMAGE_NAME }}\", \"tag\": \"${{ env.TAG }}\", \"digest\": \"${{ env.DIGEST }}\"}" > prod-build-info.json

    - name: Upload build info as artifact
      uses: actions/upload-artifact@v4
      with:
        name: prod-build-info
        path: prod-build-info.json
