name: Approve and Push to Prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy to production'
        required: false
        default: '' # Leave this blank to be set dynamically

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Build Tag
      id: vars
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        TAG="${{ github.event.inputs.tag }}"
        if [ -z "$TAG" ]; then
          TAG=$TIMESTAMP
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Display Tag for Confirmation
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "Using tag: $TAG"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Pull dev image
      run: docker pull stellarhub/dev-target:${{ env.TAG }}

    - name: Tag image for prod
      run: docker tag stellarhub/dev-target:${{ env.TAG }} stellarhub/prod-target:${{ env.TAG }}

    - name: Push prod image with provided or default tag
      run: docker push stellarhub/prod-target:${{ env.TAG }}

    - name: Push prod image with latest tag
      run: |
        docker tag stellarhub/prod-target:${{ env.TAG }} stellarhub/prod-target:latest
        docker push stellarhub/prod-target:latest

    - name: Save tag information
      run: |
        echo "Prod Tag: ${{ env.TAG }}" > prod-build-info.txt
        echo "Prod Tag: latest" >> prod-build-info.txt

    - name: Upload build info as artifact
      uses: actions/upload-artifact@v2
      with:
        name: prod-build-info
        path: prod-build-info.txt
