name: Approve and Push to Prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy to production (optional)'
        required: false
        default: '' # Leave this blank to handle dynamically

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Update to v4 for Node.js 20 support

    - name: Set up Docker Tag
      id: vars
      run: |
        if [ -z "${{ github.event.inputs.tag }}" ]; then
          TAG=latest
        else
          TAG=${{ github.event.inputs.tag }}
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Display Tag for Confirmation
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "Using tag: ${{ env.TAG }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v3 # v2 supports Node.js 20
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Pull dev image
      run: docker pull stellarhub/dev-target:${{ env.TAG }}

    - name: Tag image for prod
      run: docker tag stellarhub/dev-target:${{ env.TAG }} stellarhub/prod-target:${{ env.TAG }}

    - name: Push prod image with provided or default tag
      run: docker push stellarhub/prod-target:${{ env.TAG }}

    - name: Push prod image with latest tag
      run: |
        docker tag stellarhub/prod-target:${{ env.TAG }} stellarhub/prod-target:latest
        docker push stellarhub/prod-target:latest

    - name: Save tag information
      run: |
        echo "Prod Tag: ${{ env.TAG }}" > prod-build-info.txt
        if [ "${{ env.TAG }}" != "latest" ]; then
          echo "Prod Tag: latest" >> prod-build-info.txt
        fi

    - name: Upload build info as artifact
      uses: actions/upload-artifact@v4 # Update to v3 for Node.js 20 support
      with:
        name: prod-build-info
        path: prod-build-info.txt
