name: Approve and Push to Prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy to production'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Tag
      id: vars
      run: |
        if [ -z "${{ github.event.inputs.tag }}" ]; then
          TAG=latest
        else
          TAG=${{ github.event.inputs.tag }}
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Display Tag for Confirmation
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "Using tag: ${{ env.TAG }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Pull dev image
      run: docker pull stellarhub/dev-target:${{ env.TAG }}

    - name: Tag image for prod
      run: docker tag stellarhub/dev-target:${{ env.TAG }} stellarhub/prod-target:${{ env.TAG }}

    - name: Push prod image with provided or default tag
      run: docker push stellarhub/prod-target:${{ env.TAG }}

    - name: Push prod image with latest tag
      run: |
        docker tag stellarhub/prod-target:${{ env.TAG }} stellarhub/prod-target:latest
        docker push stellarhub/prod-target:latest

    - name: Get Docker manifest
      id: manifest
      run: |
        MANIFEST=$(docker manifest inspect stellarhub/prod-target:${{ env.TAG }})
        echo "MANIFEST=$MANIFEST" >> $GITHUB_ENV

    - name: Save tag information to JSON
      run: |
        IMAGE_NAME="stellarhub/prod-target"
        TAG=${{ env.TAG }}
        MANIFEST=${{ env.MANIFEST }}
        echo "{\"image_name\": \"$IMAGE_NAME\", \"tag\": \"$TAG\", \"manifest\": $MANIFEST}" > prod-build-info.json

    - name: Upload build info as artifact
      uses: actions/upload-artifact@v4
      with:
        name: prod-build-info
        path: prod-build-info.json
