name: Build and Push to Dev

on:
  push:
    paths:
      - '/Dockerfile' 
      - '.github/workflows/build-and-push-dev.yml' 
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Build Tag
      id: vars
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        TAG="${{ github.event.inputs.tag }}"
        if [ -z "$TAG" ]; then
          TAG=$TIMESTAMP
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Display Tag for Confirmation
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "Using tag: $TAG"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build Docker image
      run: docker build -t stellarhub/dev-target:${{ env.TAG }} .

    - name: Get image digest
      id: get_digest
      run: |
        DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' stellarhub/dev-target:${{ env.TAG }} | cut -d'@' -f2)
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV

    - name: Push Docker image with provided or default tag
      run: docker push stellarhub/dev-target:${{ env.TAG }}

    - name: Push Docker image with latest tag
      run: |
        docker tag stellarhub/dev-target:${{ env.TAG }} stellarhub/dev-target:latest
        docker push stellarhub/dev-target:latest

    - name: Save Dockerfile and tag information to JSON
      run: |
        echo "{\"image_name\": \"stellarhub/dev-target\", \"tag\": \"${{ env.TAG }}\", \"digest\": \"${{ env.DIGEST }}\"}" > build-info.json

    - name: Upload build info as artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-info
        path: build-info.json
