name: Rollback Prod
## feature for json, feeature 2, test, test2....2
on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    env:
      PROD_IMAGE_NAME: stellarhub/prod-target

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Get the previous image tag
      id: prev-tag
      run: |
        PREVIOUS_TAG=$(docker images ${{ env.PROD_IMAGE_NAME }} --format "{{.Tag}}" | sort -r | sed -n 2p)
        echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV

    - name: Pull previous image for multiple architectures
      run: |
        docker pull ${{ env.PROD_IMAGE_NAME }}:${{ env.PREVIOUS_TAG }}

    - name: Get previous image digest
      id: get_digest
      run: |
        DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.PROD_IMAGE_NAME }}:${{ env.PREVIOUS_TAG }} | cut -d'@' -f2)
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV

    - name: Tag previous image as latest
      run: docker tag ${{ env.PROD_IMAGE_NAME }}:${{ env.PREVIOUS_TAG }} ${{ env.PROD_IMAGE_NAME }}:latest

    - name: Push previous image as latest
      run: docker push ${{ env.PROD_IMAGE_NAME }}:latest

    - name: Save rollback information to JSON
      run: |
        echo "{\"image_name\": \"${{ env.PROD_IMAGE_NAME }}\", \"tag\": \"latest\", \"previous_tag\": \"${{ env.PREVIOUS_TAG }}\", \"digest\": \"${{ env.DIGEST }}\"}" > rollback-info.json

    - name: Upload rollback info as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rollback-info
        path: rollback-info.json
